server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: datacollector-backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: datacollector-backend
          __path__: /var/log/datacollector/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            service: service
      - labels:
          level:
          service:
      - timestamp:
          source: timestamp
          format: RFC3339Nano

  - job_name: datacollector-system
    static_configs:
      - targets:
          - localhost
        labels:
          job: datacollector-system
          __path__: /var/log/datacollector/system/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            component: component
      - labels:
          level:
          component:
      - timestamp:
          source: timestamp
          format: RFC3339Nano

  - job_name: docker-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-logs
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: log
            container: attrs.container_name
            image: attrs.image_name
      - labels:
          level:
          container:
          image:
      - timestamp:
          source: timestamp
          format: RFC3339Nano 