# OpenSearch configuration for DataCollector
# Simplified configuration for Windows development

cluster.name: datacollector-cluster
node.name: datacollector-node

# Network settings
network.host: 0.0.0.0
http.port: 9200

# Discovery settings
discovery.type: single-node

# Path settings
path.data: /usr/share/opensearch/data
path.logs: /usr/share/opensearch/logs

# Memory settings - disabled for Windows compatibility
bootstrap.memory_lock: false

# Security settings (disabled for development)
plugins.security.disabled: true

# HTTP settings
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "X-Requested-With,X-Auth-Token,Content-Type,Content-Length"
http.cors.allow-credentials: true

# Cluster settings
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 85%
cluster.routing.allocation.disk.watermark.high: 90%
cluster.routing.allocation.disk.watermark.flood_stage: 95%

# Index settings
indices.memory.index_buffer_size: 20%
indices.memory.min_index_buffer_size: 96mb
indices.fielddata.cache.size: 20%
indices.queries.cache.size: 10%

# Search settings
search.max_buckets: 65536
search.max_open_scroll_context: 500

# Thread pool settings
thread_pool:
  write:
    size: 2
    queue_size: 200
  search:
    size: 5
    queue_size: 1000
  get:
    size: 2
    queue_size: 1000

# Action settings
action.destructive_requires_name: true
action.auto_create_index: true

# Logging
logger.level: INFO

# Performance settings
indices.recovery.max_bytes_per_sec: 40mb
cluster.routing.allocation.node_concurrent_recoveries: 2
cluster.routing.allocation.cluster_concurrent_rebalance: 2

# Circuit breaker settings
indices.breaker.total.limit: 70%
indices.breaker.fielddata.limit: 40%
indices.breaker.request.limit: 40% 